import {
  processKingCountyResults, processNYCResults, processChicagoResults,
  processMontgomeryResults, processAustinResults, processSFResults, processLAResults,
  processDelawareResults, processNYStateResults, processTorontoResults,
  processBostonResults, processHoustonResults, processStanislausResults,
  processVancouverBCResults, processSingaporeResults, processNSWResults,
  processTacomaPierceResults, processSNHDResults, processWakeCountyResults,
  processLouisvilleResults, processRiversideResults, processAlabamaResults,
  processMaricopaResults, processArkansasResults, processTriCountyCoResults,
  processFVHDResults, processDCResults, processFloridaResults,
  processGeorgiaResults, processIllinoisCDPResults, processIndianaMarionResults,
  processBRLAResults,
  kingToDetailRows, nycToDetailRows, chicagoToDetailRows,
  montgomeryToDetailRows, austinToDetailRows, sfToDetailRows, laToDetailRows,
  delawareToDetailRows, nyStateToDetailRows, torontoToDetailRows,
  bostonToDetailRows, houstonToDetailRows, stanislausToDetailRows,
  triCountyCoToDetailRows, fvhdToDetailRows, dcToDetailRows,
  floridaToDetailRows, illinoisCDPToDetailRows, indianaMarionToDetailRows,
  brlaToDetailRows,
} from "../inspectionProcessors";

export const PROCESSORS = {
  king:          { process: processKingCountyResults,  toDetailRows: kingToDetailRows },
  nyc:           { process: processNYCResults,         toDetailRows: nycToDetailRows },
  cook:          { process: processChicagoResults,     toDetailRows: chicagoToDetailRows },
  montgomery_md: { process: processMontgomeryResults,  toDetailRows: montgomeryToDetailRows },
  travis:        { process: processAustinResults,      toDetailRows: austinToDetailRows },
  sf:            { process: processSFResults,          toDetailRows: sfToDetailRows },
  la:            { process: processLAResults,          toDetailRows: laToDetailRows },
  delaware:      { process: processDelawareResults,    toDetailRows: delawareToDetailRows },
  ny_state:         { process: processNYStateResults,     toDetailRows: nyStateToDetailRows },
  tri_county_co:    { process: processTriCountyCoResults,  toDetailRows: triCountyCoToDetailRows },
  fvhd:             { process: processFVHDResults,         toDetailRows: fvhdToDetailRows },
  dc:               { process: processDCResults,           toDetailRows: dcToDetailRows },
  florida:          { process: processFloridaResults,      toDetailRows: floridaToDetailRows },
  illinois_cdp:     { process: processIllinoisCDPResults,   toDetailRows: illinoisCDPToDetailRows },
  indiana_marion:   { process: processIndianaMarionResults, toDetailRows: indianaMarionToDetailRows },
  brla:             { process: processBRLAResults,         toDetailRows: brlaToDetailRows },
  toronto:          { process: processTorontoResults,     toDetailRows: torontoToDetailRows },
};

export const SOURCE_TO_COUNTY = {
  king: "king", nyc: "nyc", chicago: "cook",
  montgomery: "montgomery_md", austin: "travis",
  sf: "sf", la: "la", dubai: "dubai", llm: "llm",
  uk_fsa: "uk_fsa", delaware: "delaware",
  ny_state: "ny_state", toronto: "toronto",
  boston: "boston", houston: "houston",
  stanislaus: "stanislaus",
  tacoma_pierce: "pierce",
  snhd: "snhd",
  singapore: "singapore",
  australia_nsw: "sydney", australia_qld: "brisbane",
  wake: "wake",
  louisville: "jefferson_ky",
  riverside: "riverside",
  alabama: "alabama",
  maricopa: "maricopa",
  arkansas: "arkansas",
  tri_county_co: "tri_county_co",
  fvhd: "fvhd",
  dc: "dc",
  florida: "florida",
  georgia: "georgia",
  illinois_cdp: "illinois_cdp",
  indiana_marion: "indiana_marion",
  brla: "brla",
};