export const REGIONS = {
  alabama: { name: "Alabama", abbr: "AL", counties: [
    { id: "jefferson", name: "Jefferson County (Birmingham)", city: "Birmingham", hasPublicApi: false },
    { id: "mobile", name: "Mobile County", city: "Mobile", hasPublicApi: false },
    { id: "madison", name: "Madison County (Huntsville)", city: "Huntsville", hasPublicApi: false },
    { id: "montgomery", name: "Montgomery County", city: "Montgomery", hasPublicApi: false },
  ]},
  alaska: { name: "Alaska", abbr: "AK", counties: [
    { id: "anchorage", name: "Municipality of Anchorage", city: "Anchorage", hasPublicApi: false },
    { id: "fairbanks", name: "Fairbanks North Star Borough", city: "Fairbanks", hasPublicApi: false },
    { id: "juneau", name: "City & Borough of Juneau", city: "Juneau", hasPublicApi: false },
  ]},
  arizona: { name: "Arizona", abbr: "AZ", counties: [
    { id: "maricopa", name: "Maricopa County (Phoenix)", city: "Phoenix", hasPublicApi: false },
    { id: "pima", name: "Pima County (Tucson)", city: "Tucson", hasPublicApi: false },
    { id: "pinal", name: "Pinal County (Mesa/Gilbert)", city: "Florence", hasPublicApi: false },
    { id: "yavapai", name: "Yavapai County (Prescott)", city: "Prescott", hasPublicApi: false },
    { id: "coconino", name: "Coconino County (Flagstaff)", city: "Flagstaff", hasPublicApi: false },
  ]},
  arkansas: { name: "Arkansas", abbr: "AR", counties: [
    { id: "pulaski", name: "Pulaski County (Little Rock)", city: "Little Rock", hasPublicApi: false },
    { id: "benton", name: "Benton County (Bentonville)", city: "Bentonville", hasPublicApi: false },
    { id: "washington_ar", name: "Washington County (Fayetteville)", city: "Fayetteville", hasPublicApi: false },
  ]},
  california: { name: "California", abbr: "CA", counties: [
    { id: "la", name: "Los Angeles County", city: "Los Angeles", hasPublicApi: false },
    { id: "sf", name: "San Francisco County", city: "San Francisco", hasPublicApi: true },
    { id: "sandiego", name: "San Diego County", city: "San Diego", hasPublicApi: false },
    { id: "sacramento", name: "Sacramento County", city: "Sacramento", hasPublicApi: false },
    { id: "alameda", name: "Alameda County (Oakland)", city: "Oakland", hasPublicApi: false },
    { id: "orange_ca", name: "Orange County (Anaheim)", city: "Santa Ana", hasPublicApi: false },
    { id: "riverside", name: "Riverside County", city: "Riverside", hasPublicApi: false },
    { id: "sanbernardino", name: "San Bernardino County", city: "San Bernardino", hasPublicApi: false },
    { id: "santaclara", name: "Santa Clara County (San Jose)", city: "San Jose", hasPublicApi: false },
    { id: "fresno", name: "Fresno County", city: "Fresno", hasPublicApi: false },
    { id: "kern", name: "Kern County (Bakersfield)", city: "Bakersfield", hasPublicApi: false },
    { id: "ventura", name: "Ventura County", city: "Ventura", hasPublicApi: false },
  ]},
  colorado: { name: "Colorado", abbr: "CO", counties: [
    { id: "denver", name: "Denver County", city: "Denver", hasPublicApi: false },
    { id: "el_paso", name: "El Paso County (Colorado Springs)", city: "Colorado Springs", hasPublicApi: false },
    { id: "boulder", name: "Boulder County", city: "Boulder", hasPublicApi: false },
    { id: "arapahoe", name: "Arapahoe County (Aurora)", city: "Centennial", hasPublicApi: false },
    { id: "adams", name: "Adams County", city: "Brighton", hasPublicApi: false },
    { id: "larimer", name: "Larimer County (Fort Collins)", city: "Fort Collins", hasPublicApi: false },
    { id: "jefferson_co", name: "Jefferson County (Lakewood)", city: "Golden", hasPublicApi: false },
  ]},
  connecticut: { name: "Connecticut", abbr: "CT", counties: [
    { id: "hartford", name: "Hartford County", city: "Hartford", hasPublicApi: false },
    { id: "new_haven", name: "New Haven County", city: "New Haven", hasPublicApi: false },
    { id: "fairfield", name: "Fairfield County (Bridgeport)", city: "Bridgeport", hasPublicApi: false },
  ]},
  delaware: { name: "Delaware", abbr: "DE", counties: [
    { id: "new_castle", name: "New Castle County (Wilmington)", city: "Wilmington", hasPublicApi: false },
    { id: "kent", name: "Kent County (Dover)", city: "Dover", hasPublicApi: false },
    { id: "sussex", name: "Sussex County", city: "Georgetown", hasPublicApi: false },
  ]},
  dc: { name: "Washington D.C.", abbr: "DC", counties: [
    { id: "dc", name: "District of Columbia", city: "Washington D.C.", hasPublicApi: false },
  ]},
  florida: { name: "Florida", abbr: "FL", counties: [
    { id: "miami_dade", name: "Miami-Dade County", city: "Miami", hasPublicApi: false },
    { id: "broward", name: "Broward County (Fort Lauderdale)", city: "Fort Lauderdale", hasPublicApi: false },
    { id: "orange_fl", name: "Orange County (Orlando)", city: "Orlando", hasPublicApi: false },
    { id: "hillsborough", name: "Hillsborough County (Tampa)", city: "Tampa", hasPublicApi: false },
    { id: "palm_beach", name: "Palm Beach County", city: "West Palm Beach", hasPublicApi: false },
    { id: "pinellas", name: "Pinellas County (St. Petersburg)", city: "Clearwater", hasPublicApi: false },
    { id: "duval", name: "Duval County (Jacksonville)", city: "Jacksonville", hasPublicApi: false },
    { id: "polk", name: "Polk County (Lakeland)", city: "Bartow", hasPublicApi: false },
    { id: "lee", name: "Lee County (Fort Myers)", city: "Fort Myers", hasPublicApi: false },
  ]},
  georgia: { name: "Georgia", abbr: "GA", counties: [
    { id: "fulton", name: "Fulton County (Atlanta)", city: "Atlanta", hasPublicApi: false },
    { id: "dekalb", name: "DeKalb County", city: "Decatur", hasPublicApi: false },
    { id: "gwinnett", name: "Gwinnett County", city: "Lawrenceville", hasPublicApi: false },
    { id: "cobb", name: "Cobb County (Marietta)", city: "Marietta", hasPublicApi: false },
    { id: "chatham", name: "Chatham County (Savannah)", city: "Savannah", hasPublicApi: false },
    { id: "bibb", name: "Bibb County (Macon)", city: "Macon", hasPublicApi: false },
  ]},
  hawaii: { name: "Hawaii", abbr: "HI", counties: [
    { id: "honolulu", name: "City & County of Honolulu", city: "Honolulu", hasPublicApi: false },
    { id: "maui", name: "Maui County", city: "Wailuku", hasPublicApi: false },
    { id: "hawaii_county", name: "Hawaii County (Big Island)", city: "Hilo", hasPublicApi: false },
    { id: "kauai", name: "Kauai County", city: "Lihue", hasPublicApi: false },
  ]},
  idaho: { name: "Idaho", abbr: "ID", counties: [
    { id: "ada", name: "Ada County (Boise)", city: "Boise", hasPublicApi: false },
    { id: "canyon", name: "Canyon County (Nampa)", city: "Caldwell", hasPublicApi: false },
    { id: "kootenai", name: "Kootenai County (Coeur d'Alene)", city: "Coeur d'Alene", hasPublicApi: false },
  ]},
  illinois: { name: "Illinois", abbr: "IL", counties: [
    { id: "cook", name: "Cook County (Chicago)", city: "Chicago", hasPublicApi: true },
    { id: "dupage", name: "DuPage County", city: "Wheaton", hasPublicApi: false },
    { id: "lake_il", name: "Lake County", city: "Waukegan", hasPublicApi: false },
    { id: "will", name: "Will County (Joliet)", city: "Joliet", hasPublicApi: false },
    { id: "kane", name: "Kane County", city: "Geneva", hasPublicApi: false },
    { id: "sangamon", name: "Sangamon County (Springfield)", city: "Springfield", hasPublicApi: false },
  ]},
  indiana: { name: "Indiana", abbr: "IN", counties: [
    { id: "marion", name: "Marion County (Indianapolis)", city: "Indianapolis", hasPublicApi: false },
    { id: "lake_in", name: "Lake County (Gary)", city: "Gary", hasPublicApi: false },
    { id: "allen", name: "Allen County (Fort Wayne)", city: "Fort Wayne", hasPublicApi: false },
    { id: "hamilton_in", name: "Hamilton County (Carmel)", city: "Noblesville", hasPublicApi: false },
  ]},
  iowa: { name: "Iowa", abbr: "IA", counties: [
    { id: "polk_ia", name: "Polk County (Des Moines)", city: "Des Moines", hasPublicApi: false },
    { id: "linn", name: "Linn County (Cedar Rapids)", city: "Cedar Rapids", hasPublicApi: false },
    { id: "scott", name: "Scott County (Davenport)", city: "Davenport", hasPublicApi: false },
    { id: "johnson", name: "Johnson County (Iowa City)", city: "Iowa City", hasPublicApi: false },
  ]},
  kansas: { name: "Kansas", abbr: "KS", counties: [
    { id: "johnson_ks", name: "Johnson County (Overland Park)", city: "Olathe", hasPublicApi: false },
    { id: "sedgwick", name: "Sedgwick County (Wichita)", city: "Wichita", hasPublicApi: false },
    { id: "wyandotte", name: "Wyandotte County (Kansas City KS)", city: "Kansas City", hasPublicApi: false },
    { id: "shawnee", name: "Shawnee County (Topeka)", city: "Topeka", hasPublicApi: false },
  ]},
  kentucky: { name: "Kentucky", abbr: "KY", counties: [
    { id: "jefferson_ky", name: "Jefferson County (Louisville)", city: "Louisville", hasPublicApi: false },
    { id: "fayette", name: "Fayette County (Lexington)", city: "Lexington", hasPublicApi: false },
    { id: "boone", name: "Boone County", city: "Burlington", hasPublicApi: false },
  ]},
  louisiana: { name: "Louisiana", abbr: "LA", counties: [
    { id: "orleans", name: "Orleans Parish (New Orleans)", city: "New Orleans", hasPublicApi: false },
    { id: "east_baton_rouge", name: "East Baton Rouge Parish", city: "Baton Rouge", hasPublicApi: false },
    { id: "jefferson_la", name: "Jefferson Parish (Metairie)", city: "Gretna", hasPublicApi: false },
    { id: "caddo", name: "Caddo Parish (Shreveport)", city: "Shreveport", hasPublicApi: false },
  ]},
  maine: { name: "Maine", abbr: "ME", counties: [
    { id: "cumberland", name: "Cumberland County (Portland)", city: "Portland", hasPublicApi: false },
    { id: "penobscot", name: "Penobscot County (Bangor)", city: "Bangor", hasPublicApi: false },
    { id: "york", name: "York County", city: "Alfred", hasPublicApi: false },
  ]},
  maryland: { name: "Maryland", abbr: "MD", counties: [
    { id: "baltimore_city", name: "Baltimore City", city: "Baltimore", hasPublicApi: false },
    { id: "baltimore_county", name: "Baltimore County", city: "Towson", hasPublicApi: false },
    { id: "montgomery_md", name: "Montgomery County", city: "Rockville", hasPublicApi: true },
    { id: "prince_georges", name: "Prince George's County", city: "Upper Marlboro", hasPublicApi: false },
    { id: "anne_arundel", name: "Anne Arundel County (Annapolis)", city: "Annapolis", hasPublicApi: false },
    { id: "howard", name: "Howard County (Columbia)", city: "Ellicott City", hasPublicApi: false },
  ]},
  massachusetts: { name: "Massachusetts", abbr: "MA", counties: [
    { id: "suffolk", name: "Suffolk County (Boston)", city: "Boston", hasPublicApi: false },
    { id: "middlesex", name: "Middlesex County (Cambridge)", city: "Cambridge", hasPublicApi: false },
    { id: "worcester", name: "Worcester County", city: "Worcester", hasPublicApi: false },
    { id: "hampden", name: "Hampden County (Springfield)", city: "Springfield", hasPublicApi: false },
    { id: "norfolk", name: "Norfolk County (Quincy)", city: "Dedham", hasPublicApi: false },
    { id: "essex_ma", name: "Essex County (Salem/Lawrence)", city: "Salem", hasPublicApi: false },
  ]},
  michigan: { name: "Michigan", abbr: "MI", counties: [
    { id: "wayne", name: "Wayne County (Detroit)", city: "Detroit", hasPublicApi: false },
    { id: "kent", name: "Kent County (Grand Rapids)", city: "Grand Rapids", hasPublicApi: false },
    { id: "oakland", name: "Oakland County", city: "Pontiac", hasPublicApi: false },
    { id: "macomb", name: "Macomb County", city: "Mount Clemens", hasPublicApi: false },
    { id: "ingham", name: "Ingham County (Lansing)", city: "Lansing", hasPublicApi: false },
    { id: "washtenaw", name: "Washtenaw County (Ann Arbor)", city: "Ann Arbor", hasPublicApi: false },
  ]},
  minnesota: { name: "Minnesota", abbr: "MN", counties: [
    { id: "hennepin", name: "Hennepin County (Minneapolis)", city: "Minneapolis", hasPublicApi: false },
    { id: "ramsey", name: "Ramsey County (St. Paul)", city: "St. Paul", hasPublicApi: false },
    { id: "dakota", name: "Dakota County", city: "Hastings", hasPublicApi: false },
    { id: "anoka", name: "Anoka County", city: "Anoka", hasPublicApi: false },
    { id: "st_louis_mn", name: "St. Louis County (Duluth)", city: "Duluth", hasPublicApi: false },
  ]},
  mississippi: { name: "Mississippi", abbr: "MS", counties: [
    { id: "hinds", name: "Hinds County (Jackson)", city: "Jackson", hasPublicApi: false },
    { id: "harrison", name: "Harrison County (Biloxi)", city: "Gulfport", hasPublicApi: false },
    { id: "desoto", name: "DeSoto County (Southaven)", city: "Hernando", hasPublicApi: false },
  ]},
  missouri: { name: "Missouri", abbr: "MO", counties: [
    { id: "st_louis_city", name: "St. Louis City", city: "St. Louis", hasPublicApi: false },
    { id: "st_louis_county", name: "St. Louis County", city: "Clayton", hasPublicApi: false },
    { id: "jackson", name: "Jackson County (Kansas City)", city: "Kansas City", hasPublicApi: false },
    { id: "greene", name: "Greene County (Springfield)", city: "Springfield", hasPublicApi: false },
    { id: "boone_mo", name: "Boone County (Columbia)", city: "Columbia", hasPublicApi: false },
  ]},
  montana: { name: "Montana", abbr: "MT", counties: [
    { id: "yellowstone", name: "Yellowstone County (Billings)", city: "Billings", hasPublicApi: false },
    { id: "cascade", name: "Cascade County (Great Falls)", city: "Great Falls", hasPublicApi: false },
    { id: "missoula", name: "Missoula County", city: "Missoula", hasPublicApi: false },
    { id: "gallatin", name: "Gallatin County (Bozeman)", city: "Bozeman", hasPublicApi: false },
  ]},
  nebraska: { name: "Nebraska", abbr: "NE", counties: [
    { id: "douglas", name: "Douglas County (Omaha)", city: "Omaha", hasPublicApi: false },
    { id: "lancaster", name: "Lancaster County (Lincoln)", city: "Lincoln", hasPublicApi: false },
    { id: "sarpy", name: "Sarpy County (Bellevue)", city: "Papillion", hasPublicApi: false },
  ]},
  nevada: { name: "Nevada", abbr: "NV", counties: [
    { id: "clark", name: "Clark County (Las Vegas)", city: "Las Vegas", hasPublicApi: false },
    { id: "washoe", name: "Washoe County (Reno)", city: "Reno", hasPublicApi: false },
    { id: "carson", name: "Carson City", city: "Carson City", hasPublicApi: false },
  ]},
  new_hampshire: { name: "New Hampshire", abbr: "NH", counties: [
    { id: "hillsborough_nh", name: "Hillsborough County (Manchester)", city: "Manchester", hasPublicApi: false },
    { id: "rockingham", name: "Rockingham County (Nashua)", city: "Exeter", hasPublicApi: false },
    { id: "merrimack", name: "Merrimack County (Concord)", city: "Concord", hasPublicApi: false },
  ]},
  new_jersey: { name: "New Jersey", abbr: "NJ", counties: [
    { id: "essex", name: "Essex County (Newark)", city: "Newark", hasPublicApi: false },
    { id: "bergen", name: "Bergen County (Hackensack)", city: "Hackensack", hasPublicApi: false },
    { id: "hudson", name: "Hudson County (Jersey City)", city: "Jersey City", hasPublicApi: false },
    { id: "middlesex_nj", name: "Middlesex County (New Brunswick)", city: "New Brunswick", hasPublicApi: false },
    { id: "monmouth", name: "Monmouth County", city: "Freehold", hasPublicApi: false },
    { id: "ocean", name: "Ocean County (Toms River)", city: "Toms River", hasPublicApi: false },
    { id: "union_nj", name: "Union County (Elizabeth)", city: "Elizabeth", hasPublicApi: false },
    { id: "camden", name: "Camden County", city: "Camden", hasPublicApi: false },
  ]},
  new_mexico: { name: "New Mexico", abbr: "NM", counties: [
    { id: "bernalillo", name: "Bernalillo County (Albuquerque)", city: "Albuquerque", hasPublicApi: false },
    { id: "dona_ana", name: "Doña Ana County (Las Cruces)", city: "Las Cruces", hasPublicApi: false },
    { id: "santa_fe_nm", name: "Santa Fe County", city: "Santa Fe", hasPublicApi: false },
  ]},
  new_york: { name: "New York", abbr: "NY", counties: [
    { id: "nyc", name: "New York City (5 Boroughs)", city: "New York City", hasPublicApi: true },
    { id: "nassau", name: "Nassau County (Long Island)", city: "Mineola", hasPublicApi: false },
    { id: "suffolk_ny", name: "Suffolk County (Long Island)", city: "Riverhead", hasPublicApi: false },
    { id: "westchester", name: "Westchester County (White Plains)", city: "White Plains", hasPublicApi: false },
    { id: "erie", name: "Erie County (Buffalo)", city: "Buffalo", hasPublicApi: false },
    { id: "monroe_ny", name: "Monroe County (Rochester)", city: "Rochester", hasPublicApi: false },
    { id: "albany", name: "Albany County", city: "Albany", hasPublicApi: false },
    { id: "onondaga", name: "Onondaga County (Syracuse)", city: "Syracuse", hasPublicApi: false },
  ]},
  north_carolina: { name: "North Carolina", abbr: "NC", counties: [
    { id: "mecklenburg", name: "Mecklenburg County (Charlotte)", city: "Charlotte", hasPublicApi: false },
    { id: "wake", name: "Wake County (Raleigh)", city: "Raleigh", hasPublicApi: false },
    { id: "guilford", name: "Guilford County (Greensboro)", city: "Greensboro", hasPublicApi: false },
    { id: "forsyth", name: "Forsyth County (Winston-Salem)", city: "Winston-Salem", hasPublicApi: false },
    { id: "durham", name: "Durham County", city: "Durham", hasPublicApi: false },
    { id: "cumberland_nc", name: "Cumberland County (Fayetteville)", city: "Fayetteville", hasPublicApi: false },
    { id: "buncombe", name: "Buncombe County (Asheville)", city: "Asheville", hasPublicApi: false },
  ]},
  north_dakota: { name: "North Dakota", abbr: "ND", counties: [
    { id: "cass", name: "Cass County (Fargo)", city: "Fargo", hasPublicApi: false },
    { id: "burleigh", name: "Burleigh County (Bismarck)", city: "Bismarck", hasPublicApi: false },
    { id: "grand_forks", name: "Grand Forks County", city: "Grand Forks", hasPublicApi: false },
  ]},
  ohio: { name: "Ohio", abbr: "OH", counties: [
    { id: "cuyahoga", name: "Cuyahoga County (Cleveland)", city: "Cleveland", hasPublicApi: false },
    { id: "franklin", name: "Franklin County (Columbus)", city: "Columbus", hasPublicApi: false },
    { id: "hamilton_oh", name: "Hamilton County (Cincinnati)", city: "Cincinnati", hasPublicApi: false },
    { id: "summit", name: "Summit County (Akron)", city: "Akron", hasPublicApi: false },
    { id: "montgomery_oh", name: "Montgomery County (Dayton)", city: "Dayton", hasPublicApi: false },
    { id: "lucas", name: "Lucas County (Toledo)", city: "Toledo", hasPublicApi: false },
    { id: "stark", name: "Stark County (Canton)", city: "Canton", hasPublicApi: false },
  ]},
  oklahoma: { name: "Oklahoma", abbr: "OK", counties: [
    { id: "oklahoma_county", name: "Oklahoma County (Oklahoma City)", city: "Oklahoma City", hasPublicApi: false },
    { id: "tulsa", name: "Tulsa County", city: "Tulsa", hasPublicApi: false },
    { id: "cleveland_ok", name: "Cleveland County (Norman)", city: "Norman", hasPublicApi: false },
  ]},
  oregon: { name: "Oregon", abbr: "OR", counties: [
    { id: "multnomah", name: "Multnomah County (Portland)", city: "Portland", hasPublicApi: false },
    { id: "lane", name: "Lane County (Eugene)", city: "Eugene", hasPublicApi: false },
    { id: "marion_or", name: "Marion County (Salem)", city: "Salem", hasPublicApi: false },
    { id: "washington_or", name: "Washington County (Beaverton/Hillsboro)", city: "Hillsboro", hasPublicApi: false },
    { id: "clackamas", name: "Clackamas County", city: "Oregon City", hasPublicApi: false },
    { id: "jackson_or", name: "Jackson County (Medford)", city: "Medford", hasPublicApi: false },
    { id: "deschutes", name: "Deschutes County (Bend)", city: "Bend", hasPublicApi: false },
  ]},
  pennsylvania: { name: "Pennsylvania", abbr: "PA", counties: [
    { id: "philadelphia", name: "Philadelphia County", city: "Philadelphia", hasPublicApi: false },
    { id: "allegheny", name: "Allegheny County (Pittsburgh)", city: "Pittsburgh", hasPublicApi: false },
    { id: "montgomery_pa", name: "Montgomery County", city: "Norristown", hasPublicApi: false },
    { id: "bucks", name: "Bucks County", city: "Doylestown", hasPublicApi: false },
    { id: "chester_pa", name: "Chester County", city: "West Chester", hasPublicApi: false },
    { id: "lancaster_pa", name: "Lancaster County", city: "Lancaster", hasPublicApi: false },
    { id: "york_pa", name: "York County", city: "York", hasPublicApi: false },
    { id: "berks", name: "Berks County (Reading)", city: "Reading", hasPublicApi: false },
  ]},
  rhode_island: { name: "Rhode Island", abbr: "RI", counties: [
    { id: "providence", name: "Providence County", city: "Providence", hasPublicApi: false },
    { id: "kent_ri", name: "Kent County (Warwick)", city: "Warwick", hasPublicApi: false },
    { id: "washington_ri", name: "Washington County", city: "Wakefield", hasPublicApi: false },
  ]},
  south_carolina: { name: "South Carolina", abbr: "SC", counties: [
    { id: "greenville", name: "Greenville County", city: "Greenville", hasPublicApi: false },
    { id: "richland", name: "Richland County (Columbia)", city: "Columbia", hasPublicApi: false },
    { id: "charleston_sc", name: "Charleston County", city: "Charleston", hasPublicApi: false },
    { id: "spartanburg", name: "Spartanburg County", city: "Spartanburg", hasPublicApi: false },
  ]},
  south_dakota: { name: "South Dakota", abbr: "SD", counties: [
    { id: "minnehaha", name: "Minnehaha County (Sioux Falls)", city: "Sioux Falls", hasPublicApi: false },
    { id: "pennington", name: "Pennington County (Rapid City)", city: "Rapid City", hasPublicApi: false },
  ]},
  tennessee: { name: "Tennessee", abbr: "TN", counties: [
    { id: "shelby", name: "Shelby County (Memphis)", city: "Memphis", hasPublicApi: false },
    { id: "davidson", name: "Davidson County (Nashville)", city: "Nashville", hasPublicApi: false },
    { id: "knox", name: "Knox County (Knoxville)", city: "Knoxville", hasPublicApi: false },
    { id: "hamilton_tn", name: "Hamilton County (Chattanooga)", city: "Chattanooga", hasPublicApi: false },
    { id: "rutherford", name: "Rutherford County (Murfreesboro)", city: "Murfreesboro", hasPublicApi: false },
  ]},
  texas: { name: "Texas", abbr: "TX", counties: [
    { id: "harris", name: "Harris County (Houston)", city: "Houston", hasPublicApi: false },
    { id: "dallas", name: "Dallas County", city: "Dallas", hasPublicApi: false },
    { id: "travis", name: "Travis County (Austin)", city: "Austin", hasPublicApi: true },
    { id: "bexar", name: "Bexar County (San Antonio)", city: "San Antonio", hasPublicApi: false },
    { id: "tarrant", name: "Tarrant County (Fort Worth)", city: "Fort Worth", hasPublicApi: false },
    { id: "collin", name: "Collin County (Plano/Frisco)", city: "McKinney", hasPublicApi: false },
    { id: "hidalgo", name: "Hidalgo County (McAllen)", city: "Edinburg", hasPublicApi: false },
    { id: "denton", name: "Denton County", city: "Denton", hasPublicApi: false },
    { id: "el_paso_tx", name: "El Paso County", city: "El Paso", hasPublicApi: false },
    { id: "nueces", name: "Nueces County (Corpus Christi)", city: "Corpus Christi", hasPublicApi: false },
    { id: "williamson", name: "Williamson County (Round Rock)", city: "Georgetown", hasPublicApi: false },
    { id: "lubbock", name: "Lubbock County", city: "Lubbock", hasPublicApi: false },
  ]},
  utah: { name: "Utah", abbr: "UT", counties: [
    { id: "salt_lake", name: "Salt Lake County", city: "Salt Lake City", hasPublicApi: false },
    { id: "utah_county", name: "Utah County (Provo/Orem)", city: "Provo", hasPublicApi: false },
    { id: "davis", name: "Davis County (Layton)", city: "Farmington", hasPublicApi: false },
    { id: "weber", name: "Weber County (Ogden)", city: "Ogden", hasPublicApi: false },
    { id: "washington_ut", name: "Washington County (St. George)", city: "St. George", hasPublicApi: false },
  ]},
  vermont: { name: "Vermont", abbr: "VT", counties: [
    { id: "chittenden", name: "Chittenden County (Burlington)", city: "Burlington", hasPublicApi: false },
    { id: "rutland", name: "Rutland County", city: "Rutland", hasPublicApi: false },
    { id: "washington_vt", name: "Washington County (Montpelier)", city: "Montpelier", hasPublicApi: false },
  ]},
  virginia: { name: "Virginia", abbr: "VA", counties: [
    { id: "fairfax", name: "Fairfax County", city: "Fairfax", hasPublicApi: false },
    { id: "virginia_beach", name: "Virginia Beach City", city: "Virginia Beach", hasPublicApi: false },
    { id: "richmond", name: "Richmond City", city: "Richmond", hasPublicApi: false },
    { id: "arlington", name: "Arlington County", city: "Arlington", hasPublicApi: false },
    { id: "chesapeake", name: "Chesapeake City", city: "Chesapeake", hasPublicApi: false },
    { id: "norfolk", name: "Norfolk City", city: "Norfolk", hasPublicApi: false },
    { id: "chesterfield", name: "Chesterfield County", city: "Chesterfield", hasPublicApi: false },
    { id: "loudoun", name: "Loudoun County", city: "Leesburg", hasPublicApi: false },
  ]},
  washington: { name: "Washington", abbr: "WA", counties: [
    { id: "king", name: "King County (Seattle)", city: "Seattle", hasPublicApi: true },
    { id: "snohomish", name: "Snohomish County (Everett)", city: "Everett", hasPublicApi: false },
    { id: "pierce", name: "Pierce County (Tacoma)", city: "Tacoma", hasPublicApi: false },
    { id: "clark_wa", name: "Clark County (Vancouver)", city: "Vancouver", hasPublicApi: false },
    { id: "spokane", name: "Spokane County", city: "Spokane", hasPublicApi: false },
    { id: "thurston", name: "Thurston County (Olympia)", city: "Olympia", hasPublicApi: false },
    { id: "kitsap", name: "Kitsap County (Bremerton)", city: "Bremerton", hasPublicApi: false },
    { id: "whatcom", name: "Whatcom County (Bellingham)", city: "Bellingham", hasPublicApi: false },
    { id: "benton_wa", name: "Benton County (Kennewick/Richland)", city: "Kennewick", hasPublicApi: false },
    { id: "yakima", name: "Yakima County", city: "Yakima", hasPublicApi: false },
  ]},
  west_virginia: { name: "West Virginia", abbr: "WV", counties: [
    { id: "kanawha", name: "Kanawha County (Charleston)", city: "Charleston", hasPublicApi: false },
    { id: "cabell", name: "Cabell County (Huntington)", city: "Huntington", hasPublicApi: false },
    { id: "monongalia", name: "Monongalia County (Morgantown)", city: "Morgantown", hasPublicApi: false },
  ]},
  wisconsin: { name: "Wisconsin", abbr: "WI", counties: [
    { id: "milwaukee", name: "Milwaukee County", city: "Milwaukee", hasPublicApi: false },
    { id: "dane", name: "Dane County (Madison)", city: "Madison", hasPublicApi: false },
    { id: "waukesha", name: "Waukesha County", city: "Waukesha", hasPublicApi: false },
    { id: "brown", name: "Brown County (Green Bay)", city: "Green Bay", hasPublicApi: false },
    { id: "racine", name: "Racine County", city: "Racine", hasPublicApi: false },
  ]},
  wyoming: { name: "Wyoming", abbr: "WY", counties: [
    { id: "laramie", name: "Laramie County (Cheyenne)", city: "Cheyenne", hasPublicApi: false },
    { id: "natrona", name: "Natrona County (Casper)", city: "Casper", hasPublicApi: false },
    { id: "teton", name: "Teton County (Jackson)", city: "Jackson", hasPublicApi: false },
  ]},
};